name: Bug
description: Report a bug to help us improve Meteor.
title: '[Bug] '
labels: bug
body:
  - type: markdown
    value: |
      ## Before making sure your bug report

      1. Wasn't already reported.
      2. Is a valid bug (check every module and their settings).
      3. Provide as much information as possible, videos, crash reports, etc.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the issue is.
    validations:
      required: true
  - type: textarea
    id: reproducing
    attributes:
      label: Steps to reproduce
      description: How do you trigger this bug?
      value: |
        1.
        2.
        3.
        ...
      render: bash
    validations:
      required: true
  - type: input
    id: meteor-version
    attributes:
      label: Meteor Version
    validations:
      required: true
  - type: input
    id: mc-version
    attributes:
      label: Minecraft Version
    validations:
      required: true
  - type: dropdown
    id: operating-systems
    attributes:
      label: Operating System
      options:
        - macOS
        - Windows
        - Linux
    validations:
      required: true
