name: Suggesion
description: Suggest a new feature or change for Meteor.
title: '[Suggestion] '
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature/change is.
    validations:
      required: true
