name: Code Quality

on:
  pull_request:
  push:
    branches: [ master ]

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Code Inspection
        uses: JetBrains/qodana-action@v2022.2.1
        
      - name: Annotate
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
